### ISSUE TITLE
Updating puppeteer will stop this to work

### ISSUE THREAD

**Issue by Praveena0989** [sambaiz/puppeteer-lambda-starter-kit#10]
I tried updating puppeteer but without success

**Comment by Kikobeats** [comment]
I'm having the same issue, any idea? no error trace 🤔

**Comment by Kikobeats** [comment]
Maybe because puppeteer 0.13 needs `Chromium 64.0.3264.0 (r515411)`

**Comment by Kikobeats** [comment]
In addition, the chrome version to use with puppeteer is declared on `package.json`:
https://github.com/GoogleChrome/puppeteer/blob/master/package.json#L39

The script of this project is taking the last version available at chromium browsers, it could be different.

I proposed add a tiny CLI around installing process of puppeter:
https://github.com/GoogleChrome/puppeteer/pull/1652

but not sure if the bundle generated can be aws lambda compatible; The script of this projects is doing additional things, not sure why:

https://github.com/sambaiz/puppeteer-lambda-starter-kit/blob/master/chrome/buildChrome.sh#L23

@sambaiz can you clarify? 😄

**Comment by Kikobeats** [comment]
I found this script, it's very similar but version is customizable:
https://github.com/adieuadieu/serverless-chrome/blob/master/packages/lambda/builds/chromium/build/build.sh#L19

We can update our script for supporting specify the version, and then generate the version compatible with puppeteer 0.13.

**Comment by shadowfool** [comment]
You may also want to consider the api changes from .10.2 to .13, I've found that several configuration options are drastically different in .13. Changing versions might break the boilerplate code in src.

**Comment by Praveena0989** [comment]
@Kikobeats  do you know how can we change the version in that script?

**Comment by Praveena0989** [comment]
Puppeteer/Chromium guys are working on /dev/shm issue(This is the issue which makes us to use all tricks to compile chromium manually and executing it) [here](https://github.com/GoogleChrome/puppeteer/issues/1540)

**Comment by Kikobeats** [comment]
actually it was removed:
https://github.com/adieuadieu/serverless-chrome/issues/87

I think if we use the latest chrome version available + puppeteer 0.13 it should be works

**Comment by Praveena0989** [comment]
@Kikobeats  then why should we even worry about chrome version when puppeteer will install the right version of chrome?

**Comment by Praveena0989** [comment]
I downloaded latest prebuild binary from [here](https://github.com/adieuadieu/serverless-chrome/releases) and renamed and rezipped files to match previous file names and it is working perfectly with puppeteer 13

**Comment by Kikobeats** [comment]
@Praveena0989 what build, beta? thanks!

**Comment by Praveena0989** [comment]
@Kikobeats  I used beta  beta-headless-chromium-64.0.3282.71-amazonlinux-2017-03.zip
