### ISSUE TITLE
Latest release breaks semantic versioning

### ISSUE THREAD

**Issue by russelldc** [sambaiz/puppeteer-lambda-starter-kit#22]
Trying to run any npm command results in:

`npm ERR! Invalid version: "1.1.1.1"`

As far as I can tell, only 3 numbers are allowed for semantic versioning.

**Comment by russelldc** [comment]
@bonkeenu to fix this in the meantime, you can just edit the package.json file and remove the last ".1" from the version tag.

**Comment by sambaiz** [comment]
fixed
