### ISSUE TITLE
Serverless framework

### ISSUE THREAD

**Issue by sanchitbh** [sambaiz/puppeteer-lambda-starter-kit#3]
Is it possible to integrate it with the serverless framework? Also right now we have to deploy almost a 44MB file for each time we change the script (unless i'm missing something).

Is it possible to split apart the puppeteer like chromeless using a [remote proxy setup](https://github.com/graphcool/chromeless#proxy-usage)? I have some ideas on how we can do this. 

If anybody wants to collaborate please let me know.

San

**Comment by md97212** [comment]
I integrated it with serverless and webpack while using a copied version of chromium on an s3 bucket. I'm happy to collaborate.

**Comment by omri-shaiko** [comment]
@md97212 will you be able to share it? 
Thanks!

**Comment by sambaiz** [comment]
Supported Serverless.
