### ISSUE TITLE
Error when running package in windows

### ISSUE THREAD

**Issue by Rhyngoh** [sambaiz/puppeteer-lambda-starter-kit#6]
I am trying to start with this starter kit but when running 'npm run package', I get this error. `
> @ package C:\Users\msarc\coding\puppeteer\project
> npm run package-prepare && cp chrome/headless_shell.tar.gz dist && cd dist && zip -rq ../package.zip .

> @ package-prepare C:\Users\msarc\coding\puppeteer\project
> npm run lint && npm run babel && cp -r package.json dist && cd dist && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm instal  l --production

> @ lint C:\Users\msarc\coding\puppeteer\project
> eslint src

> @ babel C:\Users\msarc\coding\puppeteer\project
> rm -rf dist && mkdir dist && ./node_modules/.bin/babel src --out-dir dist

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ babel: `rm -rf dist && mkdir dist && ./node_modules/.bin/babel src --out-dir dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\msarc\AppData\Roaming\npm-cache\_logs\2017-11-06T20_13_55_486Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ package-prepare: `npm run lint && npm run babel && cp -r package.json dist && cd dist && PUPPETEER_SKIP_CHR  OMIUM_DOWNLOAD=1 npm install --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ package-prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\msarc\AppData\Roaming\npm-cache\_logs\2017-11-06T20_13_55_607Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ package: `npm run package-prepare && cp chrome/headless_shell.tar.gz dist && cd dist && zip -rq ../package.  zip .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\msarc\AppData\Roaming\npm-cache\_logs\2017-11-06T20_13_55_667Z-debug.log

`

How can I fix this error and use this starter kit?

**Comment by Mykolas-Molis** [comment]
This software only works on Linux.
